name: wompwomp_env
channels:
  - conda-forge
  - defaults
  - bioconda
  - r
dependencies:  # one day, replace all dependencies with simply bioconductor-wompwomp (once wompwomp is on bioconda)
  - r-base>=3.5.0
  - r-dplyr
  - r-ggplot2
  - r-ggforce
  - r-ggalluvial
  - r-igraph
  - r-tibble
  - r-rlang
  - r-tidyr
  - r-magrittr
  - r-data.table
  - r-reticulate
  - r-purrr
  - r-ggfittext
  - r-tsp
  - r-testthat>=3.0.0
  - r-vdiffr
  - r-magick
  - r-knitr
  - r-rmarkdown
  - r-gtools
  - r-mclust
  - r-here
  - r-ggrastr
  - r-stringr
  - r-sessioninfo
  - r-remotes
  - pip=25.1
  - python>=3.9,<3.12
  - pip:
      - numpy==1.23.5
      - splitspy==0.0.10
      - pandas==2.3.0
      - scipy==1.15.3
      - leidenalg==0.10.2
      - python-igraph==0.11.9
