name: alluvialmatch_env
channels:
  - conda-forge
  - defaults
  - bioconda
  - r
dependencies:
  - r-base>=3.5.0
  - r-dplyr
  - r-ggplot2
  - r-ggforce
  - r-ggalluvial
  - r-igraph
  - r-tibble
  - r-rlang
  - r-tidyr
  - r-magrittr
  - r-data.table
  - r-reticulate
  - r-testthat>=3.0.0
  - r-vdiffr
  - r-magick
  - r-knitr
  - r-rmarkdown
  - r-gtools
  - r-mclust
  - r-sessioninfo
  - pip=25.1
  - python=3.10
  - pip:
      - numpy==1.23.5
      - splitspy==0.0.10
