name: wompwomp_env
channels:
  - conda-forge
  - defaults
  - bioconda
  - r
dependencies:  # one day, replace all dependencies with simply bioconductor-wompwomp (once wompwomp is on bioconda)
  - r-base>=3.5.0
  - r-dplyr
  - r-ggplot2
  - r-ggforce
  - r-ggalluvial
  - r-igraph
  - r-tibble
  - r-rlang
  - r-tidyr
  - r-magrittr
  - r-data.table
  - r-purrr
  - r-ggfittext
  - r-tsp
  - r-testthat>=3.0.0
  - r-vdiffr
  - r-magick
  - r-knitr
  - r-rmarkdown
  - r-gtools
  - r-mclust
  - r-here
  - r-ggrastr
  - r-stringr
  - r-sessioninfo
  - r-remotes
