```{r}
library(tidyr)
library(tidyverse)
library(dplyr)
library(ggalluvial)
```

```{r}
find_group2_colors <- function(clus_df_gather, group1_name, group2_name) {
    ditto_colors =  c(
    "#D55E00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#E69F00", "#CC79A7", "#666666", "#AD7700", "#1C91D4", "#007756", "#D5C711", "#005685",
    "#A04700", "#B14380", "#4D4D4D", "#FFBE2D", "#80C7EF", "#00F6B3", "#F4EB71", "#06A5FF", "#FF8320", "#D99BBD", "#8C8C8C", "#FFCB57", "#9AD2F2",
    "#2CFFC6", "#F6EF8E", "#38B7FF", "#FF9B4D", "#E0AFCA", "#A3A3A3", "#8A5F00", "#1674A9", "#005F45", "#AA9F0D", "#00446B", "#803800", "#8D3666",
    "#3D3D3D"
)
    clus_df_filtered <- clus_df_gather[, c(group1_name, group2_name, "count")]
    
    clus_df_filtered[[group1_name]] <- paste0("G1_", clus_df_filtered[[group1_name]])
    clus_df_filtered[[group2_name]] <- paste0("G2_", clus_df_filtered[[group2_name]])
    
    g <- igraph::graph_from_data_frame(d = clus_df_filtered, directed = FALSE)
    igraph::V(g)$type <- ifelse(igraph::V(g)$name %in% clus_df_filtered[[group1_name]], TRUE, FALSE)
    
    matching <- igraph::max_bipartite_match(g, weights = clus_df_filtered$count)
    
    keys <- names(matching$matching)
    number_group1_clusters <- length(sub("^G1_", "", keys[grep("^G1_", keys)]))
    number_group2_clusters <- length(sub("^G2_", "", keys[grep("^G2_", keys)]))
    
    # Extract and filter the matching pairs
    non_na_pairs <- matching$matching[!is.na(matching$matching)]
    
    # Filter out pairs where S is matched to C (excluding C matched to S or NA)
    g1_to_g2_pairs <- non_na_pairs[grep("^G1_", names(non_na_pairs))]
    
    
    # Extract numeric indices from the filtered pairs
    g1_indices <- as.numeric(sub("G1_", "", names(g1_to_g2_pairs)))
    g2_indices <- as.numeric(sub("G2_", "", g1_to_g2_pairs))
    
    # Initialize the new colors vector
    group2_colors <- vector("character", number_group2_clusters)
    
    # Assign colors based on the matching
    for (i in seq_along(g1_indices)) {
        # Check if the C index is within the bounds of ditto_colors
        if (g2_indices[i] <= length(ditto_colors)) {
            group2_colors[g2_indices[i]] <- ditto_colors[g1_indices[i]]
        }
    }
    
    remaining_colors <- ditto_colors[number_group1_clusters+1:length(ditto_colors)]
    group2_colors[(group2_colors == "")] <- remaining_colors[1:sum(group2_colors == "")]
    
    return (group2_colors)
}
```

```{r}
plot_alluvial <- function(clus_df_gather, group1_name = "Seurat", group2_name = "Scanpy", group1_name_mapping = "Seurat", group2_name_mapping = "Scanpy", color_boxes = TRUE, color_bands = FALSE, alluvial_alpha = 0.5, match_colors = TRUE, save = FALSE, include_labels_in_boxes = FALSE, include_axis_titles = FALSE, show_group_2_box_labels_in_ascending = FALSE, axis_text_size=4) {
    num_levels_group1 <- length(levels(clus_df_gather[[group1_name]]))
    num_levels_group2 <- length(levels(clus_df_gather[[group2_name]]))
    
    if (show_group_2_box_labels_in_ascending) {
        group2_name_mapping <- group2_name
    }

    
    ditto_colors =  c(
    "#D55E00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#E69F00", "#CC79A7", "#666666", "#AD7700", "#1C91D4", "#007756", "#D5C711", "#005685",
    "#A04700", "#B14380", "#4D4D4D", "#FFBE2D", "#80C7EF", "#00F6B3", "#F4EB71", "#06A5FF", "#FF8320", "#D99BBD", "#8C8C8C", "#FFCB57", "#9AD2F2",
    "#2CFFC6", "#F6EF8E", "#38B7FF", "#FF9B4D", "#E0AFCA", "#A3A3A3", "#8A5F00", "#1674A9", "#005F45", "#AA9F0D", "#00446B", "#803800", "#8D3666",
    "#3D3D3D"
)
    # Extract colors for each factor, assuming ditto_colors is long enough
    colors_group1 <- ditto_colors[1:num_levels_group1]
    
    if (match_colors) {
        colors_group2 <- find_group2_colors(clus_df_gather, group1_name, group2_name)
    } else {
        colors_group2 <- ditto_colors[1:num_levels_group2]
    }

    colors_group1_reverse <- rev(colors_group1)
    colors_group2_reverse <- rev(colors_group2)

    # Combine the colors
    combined_colors <- c(colors_group1, colors_group2)
    combined_colors_reverse <- c(colors_group1_reverse, colors_group2_reverse)

    # uncomment to attempt mapping
    # p <- ggplot(data = clus_df_gather, aes(axis1 = !!sym(group1_name_mapping), axis2 = !!sym(group2_name_mapping), y = value))  # commented out as of Jan 2025
    p <- ggplot(data = clus_df_gather, aes(axis1 = !!sym(group1_name), axis2 = !!sym(group2_name), y = count))  # uncommented as of Jan 2025

    if (color_bands) {
        if (num_levels_group2 > num_levels_group1) {
            p <- p +
                geom_alluvium(aes(fill = !!sym(group2_name)), alpha = alluvial_alpha) +
                scale_fill_manual(values = colors_group2) +
                labs(fill = NULL)
        } else {
            p <- p +
                geom_alluvium(aes(fill = !!sym(group1_name)), alpha = alluvial_alpha) +
                scale_fill_manual(values = colors_group1) +
                labs(fill = NULL)
        }
    } else {
        p <- p + geom_alluvium()
    }

    if (color_boxes) {
        p <- p + geom_stratum(fill = combined_colors_reverse)
    } else {
        p <- p + geom_stratum()
    }
    
    if (include_labels_in_boxes) {
        p <- p + 
            geom_text(stat = "stratum", aes(label = after_stat(stratum)), size = 3, color = "black")
    } 
    
    if (include_axis_titles) {
        p <- p +
            annotate("text", x = 1, y = max(clus_df_gather$count) + 510, label = group1_name, size = 5, hjust = 0.5) +
            annotate("text", x = 2, y = max(clus_df_gather$count) + 510, label = group2_name, size = 5, hjust = 0.5)
    } 

    p <- p +
        # geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
        theme_void() +
        annotate("text", x = 1.023, y = 1, label = num_levels_group1, hjust = 1, vjust = 1.35, size = 5) + # Adjust x, y for Seurat
        annotate("text", x = 1.978, y = 1, label = num_levels_group2, hjust = 0, vjust = 1.35, size = 5) + # Adjust x, y for Scanpy
        theme(
            text = element_text(family = "Arial"), 
            legend.text = element_text(size = rel(axis_text_size))
        )

    if (save == TRUE || is.character(save)) {
        filepath <- make_save_path(filepath = save, default_filepath = file_paths_default$alluvial)
        ggsave(filepath, plot = p, dpi = dpi, bg = "white")
    }

    return(p)
}

```

```{r}

color_opts =  c(
    "#D55E00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#E69F00", "#CC79A7", "#666666", "#AD7700", "#1C91D4", "#007756", "#D5C711", "#005685",
    "#A04700", "#B14380", "#4D4D4D", "#FFBE2D", "#80C7EF", "#00F6B3", "#F4EB71", "#06A5FF", "#FF8320", "#D99BBD", "#8C8C8C", "#FFCB57", "#9AD2F2",
    "#2CFFC6", "#F6EF8E", "#38B7FF", "#FF9B4D", "#E0AFCA", "#A3A3A3", "#8A5F00", "#1674A9", "#005F45", "#AA9F0D", "#00446B", "#803800", "#8D3666",
    "#3D3D3D"
)
all_df <- read_csv('/workspace/test_dataframe.csv')

plot_alluvial(all_df, group1_name = 'tissue_num', group2_name = 'leiden_num', color_boxes = TRUE, color_bands = TRUE)

```