---
title: "8 cubed"
output:
    BiocStyle::html_document:
        toc: true
        toc_depth: 2
        self_contained: false
vignette: >
  %\VignetteIndexEntry{8 cubed}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r}
# devtools::load_all() # !!! erase

library(wompwomp)  #!!! uncomment
library(dplyr)
library(ggplot2)
library(ggalluvial)
library(ggforce)
library(igraph)
library(tibble)

set.seed(42)
```

```{r}
use_temp_dir <- FALSE

use_temp_dir <- (use_temp_dir || !interactive()) # ensure temp_dire when non-interactive always
output_dir <- ifelse(!use_temp_dir, here::here("vignettes", "output"), file.path(tempdir(), "vignette_output"))
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
```

```{r}
eight_cubed_grouped_file_path <- file.path(output_dir, "Akr1c21_Slc7a12_grouped.csv")
graphing_columns <- c("Gene", "individual", "Sex", "Genotype", "Tissue", "Celltype_final")

if (!file.exists(eight_cubed_grouped_file_path)) {
    stop(sprintf("8 cubed file not found, and is currently not available for download. Please place the file in '%s'", eight_cubed_grouped_file_path))
}
```

```{r}
clus_df_gather <- read.csv(eight_cubed_grouped_file_path)
clus_df_gather$value <- round(clus_df_gather$value) # round to nearest whole number
print(nrow(clus_df_gather))
clus_df_gather
```

```{r}
# unsorted_objective <- determine_crossing_edges(clus_df_gather, graphing_columns = graphing_columns, column_weights = "value", return_weighted_layer_free_objective = TRUE)
# print(unsorted_objective)

p_unsorted <- plot_alluvial(clus_df_gather, graphing_columns = graphing_columns, column_weights = "value", sorting_algorithm = "none", color_bands = TRUE, color_boxes = FALSE, coloring_algorithm = "left", resolution = 12, verbose = TRUE, output_plot_path = file.path(output_dir, "8_cubed_full_unsorted.pdf"), min_text = 0.01, save_height = 24, save_width = 24)
p_unsorted
```

```{r}
optimize_column_order <- FALSE
optimize_column_order_per_cycle <- FALSE

print(Sys.time())
p_sorted_fixed_columns <- plot_alluvial(clus_df_gather, graphing_columns = graphing_columns, column_weights = "value", sorting_algorithm = "tsp", optimize_column_order = optimize_column_order, optimize_column_order_per_cycle = optimize_column_order_per_cycle, coloring_algorithm = "left", resolution = 12, color_bands = TRUE, color_boxes = FALSE, verbose = TRUE, output_plot_path = file.path(output_dir, "8_cubed_full_NN_fixed_columns.pdf"), min_text = 0.01, save_height = 24, save_width = 24)
print(Sys.time())

p_sorted_fixed_columns
```

```{r}
optimize_column_order <- TRUE
optimize_column_order_per_cycle <- FALSE

print(Sys.time())
p_sorted_optimized_columns <- plot_alluvial(clus_df_gather, graphing_columns = graphing_columns, column_weights = "value", sorting_algorithm = "tsp", optimize_column_order = optimize_column_order, optimize_column_order_per_cycle = optimize_column_order_per_cycle, coloring_algorithm = "left", resolution = 12, color_bands = TRUE, color_boxes = FALSE, verbose = TRUE, output_plot_path = file.path(output_dir, "8_cubed_full_NN_optimized_columns.pdf"), min_text = 0.01, save_height = 24, save_width = 24)
print(Sys.time())

p_sorted_optimized_columns
```

Now remove the last column
```{r}
graphing_columns_summed <- c("Gene", "individual", "Sex", "Genotype", "Tissue")
clus_df_gather_summed <- clus_df_gather %>%
    dplyr::group_by(Gene, individual, Sex, Genotype, Tissue) %>%
    dplyr::summarise(value = sum(value), .groups = "drop")
print(nrow(clus_df_gather_summed))
```

```{r}
# clus_df_gather_summed_processed <- data_preprocess(df = clus_df_gather_summed, graphing_columns = graphing_columns_summed, column_weights = "value", load_df = FALSE, do_gather_set_data = FALSE)
# unsorted_objective_trimmed <- determine_crossing_edges(clus_df_gather_summed_processed, graphing_columns = graphing_columns_summed, column_weights = "value", return_weighted_layer_free_objective = TRUE)
# print(unsorted_objective_trimmed)

p_unsorted_trimmed <- plot_alluvial(clus_df_gather_summed, graphing_columns = graphing_columns_summed, column_weights = "value", sorting_algorithm = "none", color_bands = TRUE, color_band_column = "Gene", color_band_list = c("Akr1c21" = "#D55E00", "Slc7a12" = "#56B4E9"), color_boxes = FALSE, coloring_algorithm = "none", verbose = TRUE, output_plot_path = file.path(output_dir, "8_cubed_trimmed_unsorted.pdf"), min_text = 0.01, save_height = 24, save_width = 24)
p_unsorted_trimmed
```

```{r}
optimize_column_order <- FALSE
optimize_column_order_per_cycle <- FALSE

print(Sys.time())
p_sorted_fixed_columns_trimmed <- plot_alluvial(clus_df_gather_summed, graphing_columns = graphing_columns_summed, column_weights = "value", sorting_algorithm = "tsp", optimize_column_order = optimize_column_order, optimize_column_order_per_cycle = optimize_column_order_per_cycle, color_bands = TRUE, color_band_column = "Gene", color_band_list = c("Akr1c21" = "#D55E00", "Slc7a12" = "#56B4E9"), color_boxes = FALSE, coloring_algorithm = "none", verbose = TRUE, output_plot_path = file.path(output_dir, "8_cubed_trimmed_NN_fixed_columns.pdf"), min_text = 0.01, save_height = 24, save_width = 24)
print(Sys.time())

p_sorted_fixed_columns_trimmed
```

```{r}
optimize_column_order <- TRUE
optimize_column_order_per_cycle <- FALSE

print(Sys.time())
p_sorted_optimized_columns_trimmed <- plot_alluvial(clus_df_gather_summed, graphing_columns = graphing_columns_summed, column_weights = "value", sorting_algorithm = "tsp", optimize_column_order = optimize_column_order, optimize_column_order_per_cycle = optimize_column_order_per_cycle, color_bands = TRUE, color_band_column = "Gene", color_band_list = c("Akr1c21" = "#D55E00", "Slc7a12" = "#56B4E9"), color_boxes = FALSE, coloring_algorithm = "none", verbose = TRUE, output_plot_path = file.path(output_dir, "8_cubed_trimmed_NN_optimized_columns.pdf"), min_text = 0.01, save_height = 24, save_width = 24)

print(Sys.time())

p_sorted_optimized_columns_trimmed
```

And now remove individual as well
```{r}
graphing_columns_summed2 <- c("Gene", "Sex", "Genotype", "Tissue")
clus_df_gather_summed2 <- clus_df_gather_summed %>%
    dplyr::group_by(Gene, Sex, Genotype, Tissue) %>%
    dplyr::summarise(value = sum(value), .groups = "drop")
print(nrow(clus_df_gather_summed2))
```

```{r}
p_unsorted_trimmed2 <- plot_alluvial(clus_df_gather_summed2, graphing_columns = graphing_columns_summed2, column_weights = "value", sorting_algorithm = "none", color_bands = TRUE, color_band_column = "Gene", color_band_list = c("Akr1c21" = "#D55E00", "Slc7a12" = "#56B4E9"), color_boxes = FALSE, coloring_algorithm = "none", verbose = TRUE, output_plot_path = file.path(output_dir, "8_cubed_trimmedX2_unsorted.pdf"), text_size = 35, axis_text_size = 35, axis_text_vjust = -5, min_text = 0.01, save_height = 24, save_width = 24)
p_unsorted_trimmed2
```

```{r}
set.seed(42)
p_unsorted_trimmed_random2 <- plot_alluvial(clus_df_gather_summed2, graphing_columns = graphing_columns_summed2, column_weights = "value", sorting_algorithm = "random", color_bands = TRUE, color_band_column = "Gene", color_band_list = c("Akr1c21" = "#D55E00", "Slc7a12" = "#56B4E9"), color_boxes = FALSE, coloring_algorithm = "none", verbose = TRUE, output_plot_path = file.path(output_dir, "8_cubed_trimmedX2_unsorted_random.pdf"), text_size = 35, axis_text_size = 35, axis_text_vjust = -5, min_text = 0.01, save_height = 24, save_width = 24)
p_unsorted_trimmed_random2
```

```{r}
optimize_column_order <- FALSE
optimize_column_order_per_cycle <- FALSE

print(Sys.time())
p_sorted_fixed_columns_trimmed2 <- plot_alluvial(clus_df_gather_summed2, graphing_columns = graphing_columns_summed2, column_weights = "value", sorting_algorithm = "tsp", optimize_column_order = optimize_column_order, optimize_column_order_per_cycle = optimize_column_order_per_cycle, color_bands = TRUE, color_band_column = "Gene", color_band_list = c("Akr1c21" = "#D55E00", "Slc7a12" = "#56B4E9"), color_boxes = FALSE, coloring_algorithm = "none", verbose = TRUE, output_plot_path = file.path(output_dir, "8_cubed_trimmedX2_NN_fixed_columns.pdf"), text_size = 35, axis_text_size = 35, axis_text_vjust = -5, min_text = 0.01, save_height = 24, save_width = 24)
print(Sys.time())

p_sorted_fixed_columns_trimmed2
```

```{r}
optimize_column_order <- TRUE
optimize_column_order_per_cycle <- TRUE

print(Sys.time())
p_sorted_optimized_columns_trimmed2 <- plot_alluvial(clus_df_gather_summed2, graphing_columns = graphing_columns_summed2, column_weights = "value", sorting_algorithm = "tsp", optimize_column_order = optimize_column_order, optimize_column_order_per_cycle = optimize_column_order_per_cycle, color_bands = TRUE, color_band_column = "Gene", color_band_list = c("Akr1c21" = "#D55E00", "Slc7a12" = "#56B4E9"), color_boxes = FALSE, coloring_algorithm = "none", verbose = TRUE, output_plot_path = file.path(output_dir, "8_cubed_trimmedX2_NN_optimized_columns.pdf"), text_size = 35, axis_text_size = 35, axis_text_vjust = -5, min_text = 0.01, save_height = 24, save_width = 24)
print(Sys.time())

p_sorted_optimized_columns_trimmed2
```

```{r}
# Ensure color_band_list is a named vector
color_band_list <- c(
    "Akr1c21" = "#D55E00",
    "Slc7a12" = "#56B4E9"
)

# Make a dummy data frame just for the legend
legend_df <- data.frame(Gene = names(color_band_list))

# Plot with invisible points to show only the legend
legend_plot <- ggplot(legend_df, aes(x = 1, y = Gene, color = Gene)) +
    geom_line(linewidth = 5) +
    scale_color_manual(values = color_band_list, name = "Gene") +
    theme_void() +
    theme(legend.position = "right")

ggsave(file.path(output_dir, "8cubed_legend.pdf"), plot = legend_plot)
```

```{r}
sessioninfo::session_info()
```
