---
title: "Examples with Labeling"
output:
    BiocStyle::html_document:
        toc: true
        toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Examples with Labeling}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
# reticulate::use_condaenv("wompwomp_env", required = TRUE) # !!! erase
# devtools::load_all() # !!! erase

library(wompwomp)  #!!! uncomment
library(dplyr)
library(ggplot2)
library(ggalluvial)
library(ggforce)
library(igraph)
library(tibble)
library(tidyr)
library(reticulate)

set.seed(42)
```

Set up our python environment
```{r setup-env, eval = FALSE}
wompwomp::setup_python_env()
```

```{r check-python, include = FALSE}
if (!reticulate::py_module_available("splitspy")) {
    message("❌ 'splitspy' not found. Run wompwomp::setup_python_env() and restart R.")
    knitr::knit_exit()
}
```

We create a toy data frame that maps tissues tissues, clusters, sex, and special
```{r}
df <- data.frame(
    tissue = c(
        "BRAIN", "BRAIN", "BRAIN",
        "STOMACH", "STOMACH", "STOMACH", "STOMACH", "STOMACH", "STOMACH",
        "HEART", "HEART", "HEART", "HEART", "HEART", "HEART", "HEART",
        "T CELL", "T CELL",
        "B CELL", "B CELL", "B CELL", "B CELL", "B CELL", "B CELL", "B CELL", "B CELL", "B CELL"
    ),
    cluster = c(
        1, 1, 2,
        1, 2, 2, 2, 2, 2,
        1, 3, 3, 3, 3, 3, 3,
        4, 4,
        4, 4, 4, 4, 4, 4, 4, 4, 4
    ),
    sex = c(
        "male", "female", "male",
        "female", "male", "female", "female", "male", "female",
        "male", "female", "male", "female", "male", "female", "male",
        "female", "male",
        "female", "male", "female", "male", "female", "male", "female", "female", "male"
    ),
    special = c(
        1, 1, 0,
        1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0,
        1, 0,
        0, 0, 1, 1, 0, 1, 0, 0, 1
    )
)

# write.csv(df, file = "vignette_intro_df_ungrouped.csv", row.names = FALSE, quote = FALSE)
head(df)
```
Default Labeling
```{r}
p1 <- plot_alluvial(df, graphing_columns = c("tissue", "cluster", "sex"), sorting_algorithm = "none",
                    coloring_algorithm = "none")
p1
```

Adding a legend
```{r}
p2 <- plot_alluvial(df, graphing_columns = c("tissue", "cluster", "sex"), sorting_algorithm = "none",
                    coloring_algorithm = "none",
                    add_legend = TRUE)
p2
```

Manually Adjusting Label Text Size
```{r}
p3 <- plot_alluvial(df, graphing_columns = c("tissue", "cluster", "sex"), sorting_algorithm = "none",
                    coloring_algorithm = "none",
                    add_legend = TRUE,
                    text_size = 6, auto_adjust_text = FALSE, )
p3
```
Adjusting Label Text Size to Require Larger Labels
```{r}
p4 <- plot_alluvial(df, graphing_columns = c("tissue", "cluster", "sex"), sorting_algorithm = "none",
                    coloring_algorithm = "none",
                    add_legend = TRUE,
                    min_text = 10, auto_adjust_text = TRUE, )
p4
```
Adjusting Axis Labels
```{r}
p5 <- plot_alluvial(df, graphing_columns = c("tissue", "cluster", "sex"), sorting_algorithm = "none",
                    coloring_algorithm = "none",
                    add_legend = TRUE,
                    min_text = 10, auto_adjust_text = TRUE, 
                    keep_y_labels = TRUE, axis_text_size = 10, include_axis_titles = TRUE,
                    include_group_sizes = TRUE)
p5
```

```{r}
sessioninfo::session_info()
```


