---
title: "Introduction to alluvialmatch"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to alluvialmatch}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
devtools::load_all()
# library(alluvialmatch)
library(dplyr)
library(ggplot2)
library(ggalluvial)
library(ggforce)
library(igraph)
library(tibble)
library(tidyr)
library(reticulate)
```

Set up our python environment
```{r setup-env, eval = FALSE}
alluvialmatch::setup_python_env()
```

```{r check-python, include = FALSE}
if (!reticulate::py_module_available("splitspy")) {
    message("❌ 'splitspy' not found. Run alluvialmatch::setup_python_env() and restart R.")
    knitr::knit_exit()
}
```

We create a toy data frame that maps tissues tissues, clusters, sex, and special
```{r}
df <- data.frame(
  tissue = c(
    "BRAIN", "BRAIN", "BRAIN",
    "STOMACH", "STOMACH", "STOMACH", "STOMACH", "STOMACH", "STOMACH",
    "HEART", "HEART", "HEART", "HEART", "HEART", "HEART", "HEART",
    "T CELL", "T CELL",
    "B CELL", "B CELL", "B CELL", "B CELL", "B CELL", "B CELL", "B CELL", "B CELL", "B CELL"
  ),
  cluster = c(
    1, 1, 2,
    1, 2, 2, 2, 2, 2,
    1, 3, 3, 3, 3, 3, 3,
    4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4
  ),
  sex = c(
    "male", "female", "male",
    "female", "male", "female", "female", "male", "female",
    "male", "female", "male", "female", "male", "female", "male",
    "female", "male",
    "female", "male", "female", "male", "female", "male", "female", "female", "male"
  ),
  special = c(
    1, 1, 0,
    1, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0,
    1, 0,
    0, 0, 1, 1, 0, 1, 0, 0, 1
  )
)

# write.csv(df, file = "vignette_intro_df_ungrouped.csv", row.names = FALSE, quote = FALSE)
head(df)
```

```{r}
p1 <- plot_alluvial(df, graphing_columns = c("tissue", "cluster", "sex", "special"), sorting_algorithm = "None")
p1
```

```{r}
devtools::load_all()
p2 <- plot_alluvial(df, graphing_columns = c("tissue", "cluster", "sex"), color_band_column="special", sorting_algorithm = "None")
p2
```

#!!! TEMP
```{r}
devtools::load_all()
p2 <- plot_alluvial(df, graphing_columns = c("tissue", "cluster", "sex"), color_band_column="special", sorting_algorithm = "None")
p2
```

Now with sorting
```{r}
p3 <- plot_alluvial(df, graphing_columns = c("tissue", "cluster", "sex", "special"), sorting_algorithm = "neighbornet")
p3
```

```{r}
p4 <- plot_alluvial(df, graphing_columns = c("tissue", "cluster", "sex"), color_band_column="special", sorting_algorithm = "neighbornet")
p4
```

```{r}
sessioninfo::session_info()
```

```{r}

```

