---
title: "Quick Start: An Introduction to wompwomp"
output:
    BiocStyle::html_document:
        toc: true
        toc_depth: 2
        self_contained: false
vignette: >
  %\VignetteIndexEntry{Quick Start: An Introduction to wompwomp}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
devtools::load_all("~/Desktop/local/wompwomp")
# library(wompwomp)

set.seed(43)
```

We create a toy data frame that maps tissues (BRAIN, STOMACH, HEART, T CELL, B CELL) to clustering (1-4)
```{r}
df <- data.frame(
    tissue = c(
        "BRAIN", "BRAIN", "BRAIN",
        "STOMACH", "STOMACH", "STOMACH", "STOMACH", "STOMACH", "STOMACH",
        "HEART", "HEART", "HEART", "HEART", "HEART", "HEART", "HEART",
        "T CELL", "T CELL",
        "B CELL", "B CELL", "B CELL", "B CELL", "B CELL", "B CELL", "B CELL", "B CELL", "B CELL"
    ),
    cluster = c(
        1, 1, 2,
        1, 2, 2, 2, 2, 2,
        1, 3, 3, 3, 3, 3, 3,
        4, 4,
        4, 4, 4, 4, 4, 4, 4, 4, 4
    )
)
graphing_columns = c("tissue", "cluster")

# write.csv(df, file = "vignette_intro_df_ungrouped.csv", row.names = FALSE, quote = FALSE)
print(df)
```

Group by tissue and cluster, counting the values in a new column value
```{r}
clus_df_gather <- data_preprocess(df, cols = graphing_columns)

# write.csv(clus_df_gather, file = "vignette_intro_df_grouped.csv", row.names = FALSE, quote = FALSE)
print(clus_df_gather)
```

```{r}
clus_df_gather_tsp <- data_sort(clus_df_gather, cols = graphing_columns, wt = "value", method = "tsp")
print(clus_df_gather_tsp)
```

```{r}
# clus_df_gather_tsp <- clus_df_gather_tsp
devtools::load_all("~/Desktop/local/wompwomp")
stratum_to_color_mapping <- data_color(clus_df_gather_tsp, cols = graphing_columns, wt = "value", method = "advanced")
print(stratum_to_color_mapping)
```

```{r}
crossing_edges_out <- determine_crossing_edges(clus_df_gather_tsp, cols = graphing_columns, wt = "value")
print(crossing_edges_out$output_objective)
```

```{r}
sessionInfo()
```


```{r}
library(ggplot2)
library(ggalluvial)

plot_alluvial_wompwomp <- function(clus_df_gather, cols, wt = "value", stratum_colors = NULL) {
    if (length(cols) != 2) {
        stop("plot_alluvial_wompwomp() requires exactly 2 columns in `cols`.")
    }
    
    col1 <- cols[1]
    col2 <- cols[2]
    
    p <- ggplot(clus_df_gather,
        aes(
            y     = .data[[wt]],
            axis1 = .data[[col1]],
            axis2 = .data[[col2]]
        )
    ) +
        geom_alluvium(aes(fill = .data[[col1]]), width = 1/12) +  # alluvia color is column1
        geom_stratum(aes(fill = after_stat(stratum)), width = 1/12, color = "grey") +
        geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
        scale_x_discrete(
            limits = c(col1, col2),
            expand = c(.05, .05)
        ) +
        theme_minimal() +
        theme(legend.position = "none")
    
    if (!is.null(stratum_colors)) {
        p <- p + scale_fill_manual(values = stratum_colors)
    }
    
    return (p)
}
```

```{r}
plot_alluvial_wompwomp(clus_df_gather, graphing_columns)
```

```{r}
set.seed(43)
clus_df_gather_tsp_from_scratch <- data_sort(df, cols = graphing_columns, method = "tsp")  # sorting
stratum_to_color_mapping <- data_color(clus_df_gather_tsp_from_scratch, cols = graphing_columns, wt = "value", method = "advanced")  # coloring
stratum_colors <- make_stratum_color_list(data = clus_df_gather_tsp_from_scratch, cols = graphing_columns, mapping = stratum_to_color_mapping)  # coloring in sorted order
plot_alluvial_wompwomp(clus_df_gather_tsp_from_scratch, graphing_columns, stratum_colors = stratum_colors)
```
