// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculate_objective_fenwick_cpp
double calculate_objective_fenwick_cpp(IntegerVector y2_rank, NumericVector weight, bool weighted_metric);
RcppExport SEXP _wompwomp_calculate_objective_fenwick_cpp(SEXP y2_rankSEXP, SEXP weightSEXP, SEXP weighted_metricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type y2_rank(y2_rankSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< bool >::type weighted_metric(weighted_metricSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_objective_fenwick_cpp(y2_rank, weight, weighted_metric));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wompwomp_calculate_objective_fenwick_cpp", (DL_FUNC) &_wompwomp_calculate_objective_fenwick_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_wompwomp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
