# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_objective_fenwick_cpp <- function(y2_rank, weight, weighted_metric) {
    .Call(`_wompwomp_calculate_objective_fenwick_cpp`, y2_rank, weight, weighted_metric)
}

